import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { RouteCard } from '@/components/RouteCard';
import { Colors } from '@/constants/Colors';
import { getRecommendedRoute, starterRoutes } from '@/services/practice';
import { useLearning } from '@/context/LearningContext';
import { t } from '@/services/i18n';
import { router } from 'expo-router';
import { getDailyGoalProgress, getOverallProgress } from '@/services/progress';

export default function HomeScreen() {
  const { activeProfile, profile, progress, streak, minutesToday } = useLearning();
  const recommendedRoute = getRecommendedRoute(profile?.goals ?? []);
  const dailyGoalProgress = getDailyGoalProgress(minutesToday);
  return <Screen><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}>
    <View style={styles.header}><View><Text style={styles.eyebrow}>{t('appName')}</Text><Text style={styles.greeting}>{t('greeting')} {activeProfile} 👋</Text></View><Pressable style={styles.avatar}><Text>☺</Text></Pressable></View>
    <View style={styles.hero}><View style={styles.heroText}><Text style={styles.heroTitle}>{t('homeHeroTitle')}</Text><Text style={styles.heroDescription}>{t('homeHeroDescription')}</Text><Pressable style={styles.button} onPress={() => router.push({ pathname: '/activity/[routeId]', params: { routeId: recommendedRoute.id } })}><Text style={styles.buttonText}>{t('continuePractice')}</Text></Pressable></View><Text style={styles.heroIcon}>☀</Text></View>
    <View style={styles.stats}><View><Text style={styles.statValue}>{streak}</Text><Text style={styles.statLabel}>{t('streakDays')}</Text></View><View><Text style={styles.statValue}>{minutesToday}</Text><Text style={styles.statLabel}>{t('minutesToday')}</Text></View><View><Text style={styles.statValue}>{getOverallProgress(progress)}%</Text><Text style={styles.statLabel}>{t('progress')}</Text></View></View>
    <View style={styles.goal}><View style={styles.goalHeader}><Text style={styles.goalTitle}>{t('dailyGoal')}</Text><Text style={styles.goalValue}>{minutesToday}/10 min</Text></View><View style={styles.goalTrack}><View style={[styles.goalFill, { width: `${dailyGoalProgress}%` }]} /></View><Text style={styles.goalHint}>{dailyGoalProgress === 100 ? t('dailyGoalComplete') : 'Practica unos minutos para completar tu objetivo.'}</Text></View>
    <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{t('recommendedRoute')}</Text><Text style={styles.link}>{recommendedRoute.title}</Text></View>
    <RouteCard route={recommendedRoute} progress={(progress.routeScores[recommendedRoute.id] ?? 0) / 100} onPress={() => router.push({ pathname: '/activity/[routeId]', params: { routeId: recommendedRoute.id } })} />
    <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{t('yourRoutes')}</Text><Text style={styles.link}>{t('seeAll')}</Text></View>
    {starterRoutes.filter((route) => route.id !== recommendedRoute.id).map((route) => <RouteCard key={route.id} route={route} progress={(progress.routeScores[route.id] ?? 0) / 100} onPress={() => router.push({ pathname: '/activity/[routeId]', params: { routeId: route.id } })} />)}
  </ScrollView></Screen>;
}

const styles = StyleSheet.create({ scroll: { paddingTop: 20, paddingBottom: 24 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }, eyebrow: { color: Colors.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1.5 }, greeting: { color: Colors.ink, fontSize: 25, fontWeight: '800', marginTop: 5 }, avatar: { backgroundColor: '#E7E1FF', width: 46, height: 46, borderRadius: 16, justifyContent: 'center', alignItems: 'center' }, hero: { backgroundColor: Colors.primary, borderRadius: 24, padding: 20, flexDirection: 'row', overflow: 'hidden', marginBottom: 16 }, heroText: { flex: 1 }, heroTitle: { color: '#FFF', fontSize: 20, fontWeight: '800', lineHeight: 26 }, heroDescription: { color: '#E5E0FF', fontSize: 13, lineHeight: 19, marginTop: 7 }, button: { backgroundColor: '#FFF', paddingVertical: 11, paddingHorizontal: 14, alignSelf: 'flex-start', borderRadius: 12, marginTop: 16 }, buttonText: { color: Colors.primary, fontWeight: '700', fontSize: 12 }, heroIcon: { color: '#BFB3FF', fontSize: 74, marginTop: 14, marginRight: -12 }, stats: { flexDirection: 'row', justifyContent: 'space-around', backgroundColor: Colors.card, borderRadius: 18, paddingVertical: 17, marginBottom: 16 }, statValue: { textAlign: 'center', color: Colors.ink, fontSize: 20, fontWeight: '800' }, statLabel: { textAlign: 'center', color: Colors.muted, fontSize: 11, marginTop: 4 }, goal: { backgroundColor: Colors.card, borderRadius: 18, padding: 16, marginBottom: 24 }, goalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, goalTitle: { color: Colors.ink, fontWeight: '800' }, goalValue: { color: Colors.primary, fontWeight: '800', fontSize: 12 }, goalTrack: { backgroundColor: '#ECEAF5', height: 8, borderRadius: 4, marginTop: 12, overflow: 'hidden' }, goalFill: { backgroundColor: Colors.success, height: '100%', borderRadius: 4 }, goalHint: { color: Colors.muted, fontSize: 12, marginTop: 9 }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, sectionTitle: { color: Colors.ink, fontSize: 19, fontWeight: '800' }, link: { color: Colors.primary, fontSize: 13, fontWeight: '700' }, });
