import { Pressable, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Screen } from '@/components/Screen';
import { Colors } from '@/constants/Colors';
import { useLearning } from '@/context/LearningContext';
import { Goal } from '@/services/onboarding';
import { TranslationKey, t } from '@/services/i18n';

const goalLabels: Record<Goal, TranslationKey> = { pronunciation: 'goalPronunciation', language: 'goalLanguage', voice: 'goalVoice', memory: 'goalMemory', reading: 'goalReading' };

export default function ProfileScreen() {
  const { activeProfile, profile, profiles, setActiveProfile } = useLearning();
  const initial = activeProfile.charAt(0).toUpperCase() || '?';
  const visibleProfiles = profiles.length ? profiles : profile ? [profile] : [];

  return <Screen><View style={styles.content}><Text style={styles.title}>Mi perfil</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{initial}</Text></View><Text style={styles.name}>{activeProfile}</Text><Text style={styles.meta}>{profile?.userType === 'child' ? 'Perfil infantil' : profile?.userType === 'olderAdult' ? 'Perfil adulto mayor' : 'Perfil personal'} · {profile?.ageRange ?? 'Edad no indicada'}</Text></View><Text style={styles.section}>{t('profileGoals')}</Text><View style={styles.goals}>{(profile?.goals ?? []).map((goal) => <View style={styles.goal} key={goal}><Text style={styles.goalText}>{t(goalLabels[goal])}</Text></View>)}</View><View style={styles.menu}><View style={styles.menuSection}><Text style={styles.menuTitle}>👥  Perfiles familiares</Text>{visibleProfiles.map((item) => <Pressable key={item.name} style={[styles.profileItem, item.name === activeProfile && styles.profileItemActive]} onPress={() => setActiveProfile(item.name)}><Text style={[styles.itemText, item.name === activeProfile && styles.itemTextActive]}>{item.name}</Text><Text style={styles.itemArrow}>{item.name === activeProfile ? '✓' : '›'}</Text></Pressable>)}</View><Pressable style={styles.addProfileButton} onPress={() => router.push('/onboarding')}><Text style={styles.addProfileText}>+ Añadir perfil</Text></Pressable><Text style={styles.item}>🎯  Mis objetivos <Text>›</Text></Text><Text style={styles.item}>🔔  Notificaciones <Text>›</Text></Text><Text style={styles.item}>⚙️  Configuración <Text>›</Text></Text></View></View></Screen>;
}
const styles = StyleSheet.create({ content: { paddingTop: 28 }, title: { color: Colors.ink, fontSize: 28, fontWeight: '800' }, profile: { alignItems: 'center', marginTop: 28 }, avatar: { width: 82, height: 82, borderRadius: 28, backgroundColor: '#E7E1FF', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: Colors.primary, fontSize: 36, fontWeight: '800' }, name: { color: Colors.ink, fontSize: 20, fontWeight: '800', marginTop: 12 }, meta: { color: Colors.muted, marginTop: 4 }, section: { color: Colors.ink, fontSize: 18, fontWeight: '800', marginTop: 28, marginBottom: 12 }, goals: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, goal: { backgroundColor: '#EAF5FF', borderRadius: 12, paddingVertical: 9, paddingHorizontal: 12 }, goalText: { color: Colors.primary, fontSize: 12, fontWeight: '700' }, menu: { backgroundColor: Colors.card, borderRadius: 20, paddingHorizontal: 18, marginTop: 28 }, menuSection: { paddingVertical: 12 }, menuTitle: { color: Colors.ink, fontSize: 15, fontWeight: '700', marginBottom: 8 }, profileItem: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10, borderBottomColor: Colors.border, borderBottomWidth: 1 }, profileItemActive: { backgroundColor: '#F0EEFF', borderRadius: 12, paddingHorizontal: 10 }, itemText: { color: Colors.ink, fontSize: 15 }, itemTextActive: { color: Colors.primary, fontWeight: '700' }, itemArrow: { color: Colors.primary, fontSize: 18 }, addProfileButton: { backgroundColor: '#EAF5FF', borderRadius: 12, paddingVertical: 10, paddingHorizontal: 12, marginBottom: 10 }, addProfileText: { color: Colors.primary, fontWeight: '700' }, item: { color: Colors.ink, fontSize: 15, paddingVertical: 18, borderBottomColor: Colors.border, borderBottomWidth: 1 } });
