import { StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { Colors } from '@/constants/Colors';
import { useLearning } from '@/context/LearningContext';
import { Goal } from '@/services/onboarding';
import { TranslationKey, t } from '@/services/i18n';

const goalLabels: Record<Goal, TranslationKey> = { pronunciation: 'goalPronunciation', language: 'goalLanguage', voice: 'goalVoice', memory: 'goalMemory', reading: 'goalReading' };

export default function ProfileScreen() { const { activeProfile, profile } = useLearning(); const initial = activeProfile.charAt(0).toUpperCase() || '?'; return <Screen><View style={styles.content}><Text style={styles.title}>Mi perfil</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{initial}</Text></View><Text style={styles.name}>{activeProfile}</Text><Text style={styles.meta}>{profile?.userType === 'child' ? 'Perfil infantil' : profile?.userType === 'olderAdult' ? 'Perfil adulto mayor' : 'Perfil personal'} · {profile?.ageRange ?? 'Edad no indicada'}</Text></View><Text style={styles.section}>{t('profileGoals')}</Text><View style={styles.goals}>{(profile?.goals ?? []).map((goal) => <View style={styles.goal} key={goal}><Text style={styles.goalText}>{t(goalLabels[goal])}</Text></View>)}</View><View style={styles.menu}><Text style={styles.item}>👥  Perfiles familiares <Text>›</Text></Text><Text style={styles.item}>🎯  Mis objetivos <Text>›</Text></Text><Text style={styles.item}>🔔  Notificaciones <Text>›</Text></Text><Text style={styles.item}>⚙️  Configuración <Text>›</Text></Text></View></View></Screen>; }
const styles = StyleSheet.create({ content: { paddingTop: 28 }, title: { color: Colors.ink, fontSize: 28, fontWeight: '800' }, profile: { alignItems: 'center', marginTop: 28 }, avatar: { width: 82, height: 82, borderRadius: 28, backgroundColor: '#E7E1FF', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: Colors.primary, fontSize: 36, fontWeight: '800' }, name: { color: Colors.ink, fontSize: 20, fontWeight: '800', marginTop: 12 }, meta: { color: Colors.muted, marginTop: 4 }, section: { color: Colors.ink, fontSize: 18, fontWeight: '800', marginTop: 28, marginBottom: 12 }, goals: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, goal: { backgroundColor: '#EAF5FF', borderRadius: 12, paddingVertical: 9, paddingHorizontal: 12 }, goalText: { color: Colors.primary, fontSize: 12, fontWeight: '700' }, menu: { backgroundColor: Colors.card, borderRadius: 20, paddingHorizontal: 18, marginTop: 28 }, item: { color: Colors.ink, fontSize: 15, paddingVertical: 18, borderBottomColor: Colors.border, borderBottomWidth: 1 } });
