import { StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { Colors } from '@/constants/Colors';
import { useLearning } from '@/context/LearningContext';
import { getOverallProgress } from '@/services/progress';
import { starterRoutes } from '@/services/practice';
import { getAchievements, getLevel, getLevelProgress } from '@/services/achievements';

export default function ProgressScreen() {
	const { progress } = useLearning();
	const overallProgress = getOverallProgress(progress);
	const recentSessions = progress.sessions.slice(-3).reverse();
	const achievements = getAchievements(progress);
	const levelProgress = getLevelProgress(progress.xp);
	return <Screen><View style={styles.content}><Text style={styles.title}>Tu progreso</Text><Text style={styles.subtitle}>Cada práctica cuenta.</Text><View style={styles.score}><Text style={styles.scoreLabel}>NIVEL {getLevel(progress.xp)}</Text><Text style={styles.scoreValue}>{progress.xp} XP</Text><View style={styles.track}><View style={[styles.fill, { width: `${levelProgress}%` }]} /></View><Text style={styles.scoreHint}>{overallProgress ? `Progreso general: ${overallProgress}%.` : 'Completa una actividad para iniciar tu progreso.'}</Text></View><View style={styles.stats}><Stat label="Racha actual" value={`${progress.currentStreak} días`} /><Stat label="Minutos hoy" value={String(progress.minutesToday)} /></View><Text style={styles.section}>Logros</Text>{achievements.map((achievement) => <View style={[styles.achievement, !achievement.unlocked && styles.locked]} key={achievement.id}><Text style={styles.badge}>{achievement.unlocked ? '★' : '○'}</Text><View><Text style={styles.achievementTitle}>{achievement.title}</Text><Text style={styles.achievementText}>{achievement.unlocked ? 'Completado' : achievement.description}</Text></View></View>)}{recentSessions.length > 0 && <><Text style={styles.section}>Actividad reciente</Text>{recentSessions.map((session, index) => <View style={styles.session} key={`${session.date}-${session.routeId}-${index}`}><View><Text style={styles.sessionTitle}>{starterRoutes.find((route) => route.id === session.routeId)?.title ?? 'Práctica'}</Text><Text style={styles.sessionDate}>{session.date}</Text></View><Text style={styles.sessionScore}>{session.score} pts</Text></View>)}</>}</View></Screen>;
}

function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({ content: { paddingTop: 28 }, title: { color: Colors.ink, fontSize: 28, fontWeight: '800' }, subtitle: { color: Colors.muted, marginTop: 6 }, score: { backgroundColor: Colors.card, borderRadius: 22, padding: 22, marginTop: 24 }, scoreLabel: { color: Colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, scoreValue: { color: Colors.primary, fontSize: 44, fontWeight: '800', marginTop: 10 }, track: { backgroundColor: '#ECEAF5', height: 10, borderRadius: 5, marginTop: 10 }, fill: { backgroundColor: Colors.primary, width: '70%', height: '100%', borderRadius: 5 }, scoreHint: { color: Colors.muted, marginTop: 12 }, stats: { flexDirection: 'row', gap: 12, marginTop: 14 }, stat: { backgroundColor: Colors.card, borderRadius: 16, flex: 1, padding: 16 }, statValue: { color: Colors.primary, fontSize: 20, fontWeight: '800' }, statLabel: { color: Colors.muted, fontSize: 12, marginTop: 4 }, section: { color: Colors.ink, fontSize: 19, fontWeight: '800', marginTop: 28, marginBottom: 12 }, achievement: { backgroundColor: '#FFF3DF', borderRadius: 18, padding: 18, flexDirection: 'row', alignItems: 'center', marginBottom: 8 }, locked: { backgroundColor: Colors.card, borderWidth: 1, borderColor: Colors.border }, badge: { color: Colors.warning, fontSize: 28, marginRight: 14 }, achievementTitle: { color: Colors.ink, fontWeight: '800' }, achievementText: { color: Colors.muted, fontSize: 12, marginTop: 4 }, session: { backgroundColor: Colors.card, borderRadius: 16, padding: 16, marginBottom: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sessionTitle: { color: Colors.ink, fontWeight: '700' }, sessionDate: { color: Colors.muted, fontSize: 12, marginTop: 4 }, sessionScore: { color: Colors.primary, fontWeight: '800' } });
